version: 2
updates:
  - package-ecosystem: "gradle" 
    directory: "/MatchingGame" 
    schedule:
      interval: "daily"
    # allow:
    #   - dependency-name: "window"
    #   - dependency-name: "compose"